// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://pvjyynetewutbsxfuils.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2anl5bmV0ZXd1dGJzeGZ1aWxzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzE5NjU1MTAsImV4cCI6MjA0NzU0MTUxMH0.t6EyagcqzW3ZzdCaOZOgiRP-IIZJoXMkPursNkbd4HE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);